Lesson 12
MarynaNogtieva/qna pull request #12
Opened 2018-03-23 03:54 UTC by MarynaNogtieva

2018-03-23 09:19 UTC, vkurennov requested changes

2018-03-23 09:19 UTC, vkurennov commented on app/views/common/confirm_mail.html.slim
> +     = label_tag :email
Т.к. это generic form (не связана с объектом), то тут label не связываются автоматически с полями для ввода. Поэтому capybara не может найти по заголовку поле. Тут нужно прописать `label_tag 'auth[info]', 'Email'`
И проверь, чтобы в результате атрибут for тега label совпадал с атриубтом name у поля ввода. Тогда метка и поле будут связаны и capybara сможет найти поле по имени

2018-03-23 09:19 UTC, vkurennov commented on app/views/common/confirm_mail.html.slim
> +     = email_field 'auth[info]', :email
Здесь нужно убрать второй параметр (:email).

2018-03-23 09:19 UTC, vkurennov commented on app/views/common/confirm_mail.html.slim
> +     = hidden_field_tag 'auth[provider]', auth.provider
Плохое решение. Это секретные данные, которые провайдер сообщает твоему серверу, их нельзя выставлять наружу, даже в скрытом виде. Сохрани их в сессии - она шифруется.

2018-03-23 13:06 UTC, MarynaNogtieva commented on app/views/common/confirm_mail.html.slim
> +     = email_field 'auth[info]', :email
if I remove :email, I'm getting an error

<img width="989" alt="screen shot 2018-03-23 at 9 05 45 am" src="https://user-images.githubusercontent.com/16690352/37830727-73bf4082-2e79-11e8-9133-8dfe360e2da8.png">

2018-03-23 13:08 UTC, MarynaNogtieva commented on app/views/common/confirm_mail.html.slim
> +     = label_tag :email
this worked for me:

```
= form_tag auth_register_path, method: :post do
  .form-group
     = label_tag 'auth[info][email]', 'Email'
     = email_field 'auth[info]', :email
     = hidden_field_tag 'auth[provider]', auth.provider
     = hidden_field_tag 'auth[uid]', auth.uid

  = submit_tag 'Confirm email'
```

2018-03-29 09:12 UTC, vkurennov approved these changes

2018-04-01 22:02 UTC, merged