lesson-13 add CanCan
MarynaNogtieva/qna pull request #13
Opened 2018-04-04 01:43 UTC by MarynaNogtieva

2018-04-04 08:21 UTC, vkurennov requested changes

2018-04-04 08:21 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
Сделай обработку ошибки авторизации для всех типов запросов (html, js, json). для js и json можно возвращать 403 статус (forbidden), на клиенте его перехватывать и выводить сообщение

2018-04-04 08:21 UTC, vkurennov commented on app/models/ability.rb
> +    can :update_destory, [ Question, Answer ], { user: user }
Лучше по user_id сравнивать, чтобы не грузить из базы ассоциацию

2018-04-04 08:21 UTC, vkurennov commented on app/models/ability.rb
> +    can :vote, [Question, Answer] do |item|
Тут для голосования и для отмены разные правила: для создания голоса юзер не должен быть автором объекта, за который голосует, а для отмены - должен быть автором созданного **голоса**.

2018-04-04 08:21 UTC, vkurennov commented on app/views/layouts/application.html.erb
>          <li>
Стоило лейаут тоже перевести на slim

2018-04-04 13:28 UTC, MarynaNogtieva commented on app/models/ability.rb
> +    can :vote, [Question, Answer] do |item|
don't understand this part 
>а для отмены - должен быть автором созданного голоса.
initially we set reset button to be available to the signed in user, who is not the author of the resource(answer or question), we did not check if user is an author of the vote

2018-04-04 14:47 UTC, vkurennov requested changes

2018-04-04 14:47 UTC, vkurennov commented on app/models/ability.rb
> +        item.votes.each do |vote|
Плохое решение. Зачем перебирать все голоса у объекта? Ведь скорее всего окажется, что как минимум один голос не от этого залогиненного юзера, ведь это голоса за объект от **всех юзеров**. Ну и кроме того, вся эта конструкция, начиная с if вернет true, потому что each возвращает итерируемую коллекцию, а не то, что написано внутри each. А коллекция будет восприниматься как true

2018-04-04 21:35 UTC, MarynaNogtieva commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
fixed

2018-04-05 07:53 UTC, vkurennov approved these changes

2018-04-05 07:53 UTC, vkurennov commented on app/models/ability.rb
> +      item.votes.where(user: user, votable_id: item.id) && !user.author_of?(item)
Опять не совсем верно. У vote же полиморфная связь, поэтому искать только по votable_id не корректно, потому что там могут быть как id вопросов, так и id ответов.
К счастью, релься сами прикрасно умеют работать с полиморфной связью, если передавать объекты, например, `where(votable: item)`

2018-04-05 13:25 UTC, merged