Lesson 7
MarynaNogtieva/qna pull request #6
Opened 2018-01-15 19:41 UTC by MarynaNogtieva

2018-01-16 05:21 UTC, iBublik requested changes

2018-01-16 05:21 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      @answer.mark_best_answer if @question.answers.include? @answer
Не проще ли искать ответ среди ответов вопроса (`@question.answers.find(...)`). Тогда и проверок никаких не требуется

2018-01-16 05:21 UTC, iBublik commented on app/controllers/questions_controller.rb
> +
Зачем тут пустая строка?

2018-01-16 05:21 UTC, iBublik commented on app/models/answer.rb
> +  scope :sort_by_best_answer, -> {order(best: :desc)}
Зачем в именах методов дублировать имя класса? Мы ведь будем вызывать их как-то так: `Answer. sort_by_best_answer`, `question.answers.sort_by_best_answer`. Это дублирование глаза мозолит, получается масло масляное.

2018-01-16 05:21 UTC, iBublik commented on app/models/answer.rb
> +      update!(best: true)
Подход абсолютно верный, но учти, что здесь есть небольшой косяк. Если текущий ответ уже является "лучшим", то строкой выше ты снимешь с него этот флаг. Но в памяти он по-прежнему будет "лучшим", и текущая строка запрос не отправит (рельса не отправляет запросов, которые ничего не изменили в модели). Таким образом, лучший ответ просто пропадет :)
В рамках учебного приложения это можно не править, но знай о такой особенности

2018-01-16 05:21 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +  - if user_signed_in? && current_user&.author_of?(answer)
Ты первым условием уже проверила, что пользователь залогинен, так что во втором условии`&` лишний.
Хотя можно просто избавиться от первого условия и писать `if current_user&.author_of?(answer)`

2018-01-16 05:21 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +      /! How to make @answer instead of answer if possible?
А зачем так делать? В партиалах не принято использовать инстанс переменные, потому что потом не разобраться откуда они приходят. Все зависимости передаются явно

2018-01-16 05:21 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +      /! How to make @answer instead of answer if possible?
А зачем так делать? В партиалах не принято использовать инстанс переменные, потому что потом не разобраться откуда они приходят. Все зависимости передаются явно

2018-01-16 05:21 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +      p= link_to 'Delete Answer', question_answer_path(@question, answer), remote: true, method: :delete, data: { confirm: "Are you sure you wnt to delete this answer?" }
Плохо, что тут используется инстанс переменная. Причину выше описал. Есть 2 варианта как это поправить:
1. Ответ уже связан с вопросом, можно писать `question_answer_path(answer.question, answer)`
2. Сделать ресурсы вложенными (см. опцию shallow для роутов). Тогда для просмотра/удаления/редактирования пути не будут требовать родительского ресурса (вопроса), и будут выглядеть так `/answers/1` (вместо `/questions/1/answers/1`)

2й вариант более удобный, на мой взгляд

2018-01-16 05:21 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +        =form_for [@question, answer], remote: true do |form|
Правило очень простое - в любом партиале (даже самом тривиальном) надо использовать _только_ инстанс переменные
См. мои рекомендации к ссылке на удаление

2018-01-16 05:21 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +  - if user_signed_in? && current_user&.author_of?(@question) && !answer.best?
Тут снова бессмысленная проверка `user_signed_in?`

2018-01-16 05:21 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answer.destroy if current_user.author_of?(@answer)
Даже если пользователь не является автором, будет отрендерен destroy.js.erb, и ответ удалится со страницы пользователя (хотя в БД ничего не поменяется)

2018-01-16 05:21 UTC, iBublik commented on app/views/answers/create.js.erb
>  $('.answers').append('<%= j render @answer %>');
Из-за неправильных отступов сначала не понял, что это тело else-ветки. Поправь

2018-01-16 05:21 UTC, iBublik commented on spec/acceptance/answers/mark_best_answer_spec.rb
> +    scenario 'Can mark best answer', js: true do
Еще нужно проверить, что лучший ответ становится первым в списке (для этого надо выбрать лучшим тот ответ, что не был первым в списке)

2018-01-16 05:21 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +    before { answer } #why do we use before here?
Это скорее к тебе вопрос :) Обычно так делают с помощью `given!/let!` хелперов, чтоб на начала теста код был уже выполнен. Например, чтоб список ответов был уже в БД, иначе при заходе на страницу вопроса там будет пусто. Но в данном случае я не увидел, где такое поведение требуется.

2018-01-16 05:21 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +      expect(answer.best).to be true
`expect(answer).to be_best` - RSpec генерирует матчеры для методов-предикатов, так тесты выглядят более читабельно

2018-01-16 05:21 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +        other_user = create(:user)
Зачем создавать юзера? Просто создай вопрос, пользователя не передавай, тогда фабрика сама его сгенерирует

2018-01-16 05:21 UTC, iBublik commented on app/models/answer.rb
> +  def mark_best_answer
Аналогичное замечание по неймингу.
А еще нет тестов на этот метод

2018-01-16 15:04 UTC, MarynaNogtieva commented on app/controllers/answers_controller.rb
> +    @answer.destroy if current_user.author_of?(@answer)
If user is not an author, he/she will not see "delete" button

2018-01-16 17:33 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answer.destroy if current_user.author_of?(@answer)
Это не мешает пользователю отправить запрос из консоли :) не критичный недостаток, но все же

2018-01-23 06:19 UTC, iBublik requested changes

2018-01-23 06:19 UTC, iBublik commented on app/controllers/answers_controller.rb
> +        format.html { render nothing: true, notice: 'Only an author of the answer can delete it' }
Не понимаю, зачем тут обработка html-формата, когда у нас удаление через js?

2018-01-23 06:19 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      @answer.mark_best if @question.answers.include? @answer
[Это замечание](https://github.com/MarynaNogtieva/qna/pull/6#discussion_r161660499) проигнорировано, а зря - это более простой и естественный способ избежать проверки

2018-01-23 06:19 UTC, iBublik commented on app/controllers/questions_controller.rb
> +
Актуально

2018-01-23 06:19 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +      p= link_to 'Delete Answer', question_answer_path(@question, answer), remote: true, method: :delete, data: { confirm: "Are you sure you wnt to delete this answer?" }
Нужно явно передавать _все_ зависимости. Запомни правило - не использовать в партиалах инстанс-переменные, только локальные! 
Тут вообще можно получить вопрос из ответа (`answer.question`). Либо сделать еще проще - использовать shallow ресурсы. Тогда для удаления и редактирования вопрос в url вообще не нужен

2018-01-23 06:19 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +      p= link_to 'Delete Answer', question_answer_path(@question, answer), remote: true, method: :delete, data: { confirm: "Are you sure you wnt to delete this answer?" }
В общем, [это замечание](https://github.com/MarynaNogtieva/qna/pull/6#discussion_r161661386) актуально

2018-01-23 06:19 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +      =form_for [@question, answer], remote: true do |form|
И снова [замечание](https://github.com/MarynaNogtieva/qna/pull/6#discussion_r161661528) проигнорировано

2018-01-23 06:19 UTC, iBublik commented on app/views/questions/errors.js.erb
> +$('#errors').html('<%= j render 'common/errors', resource: @answer %>');
Что-то я вообще запутался, где эта вьюха используется? Почему она лежит в папке questions, а ресурс передается `@answer`?

2018-01-23 06:19 UTC, iBublik commented on spec/acceptance/answers/mark_best_answer_spec.rb
> +        within "#answer-id-#{answer.id}" do
Нет гарантии, что ответ явяляется не первым на странице. Сначала нужно это проверить

2018-01-23 06:19 UTC, iBublik commented on spec/acceptance/answers/mark_best_answer_spec.rb
> +        second_answer_index = page.body.index(another_answer.body)
Неочевидно сделано. Лучше использовать псевдоклассы css или просто выбрать все ответы (см. метод all) - это будет массив - и проверить тело первого

2018-01-23 06:19 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +      expect(answer.best).to be true
Настоятельно рекомендую использовать этот синтаксис - логика проверки более понятна становится

2018-01-23 06:19 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +        other_user = create(:user)
Вопрос актуален

2018-01-23 11:41 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +        =form_for [@question, answer], remote: true do |form|
@MarynaNogtieva поправил комментарий, извиняюсь :)

2018-01-25 08:32 UTC, vkurennov approved these changes

2018-01-25 08:32 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      =form_for [answer], remote: true do |form|
Массив не нужен, раз тут один элемент

2018-01-25 08:32 UTC, vkurennov commented on app/views/answers/best_answer.js.erb
> +$('.answers').html('<%= j render @answer.question.answers.sort_by_best%>')
Не очень красивая запись, вообще обращение к ассоциациям родительского объекта чаще всего плохая идея. Лучше установи в контроллере переменную `@question` и тут ее используй.

2018-01-25 14:05 UTC, MarynaNogtieva commented on app/views/answers/best_answer.js.erb
> +$('.answers').html('<%= j render @answer.question.answers.sort_by_best%>')
done

2018-01-25 14:06 UTC, merged